apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: appsec
  name: security-champion-stats-backend
  namespace: appsec
spec:
  image: "{{ image }}"
  port: 8080
  env:
    - name: SLACK_SC_CHANNEL_ID
      value: CN8N938K1
    - name: SLACK_MEMBERSHIP_ENABLED
      value: "true"
    - name: SLACK_MEMBERSHIP_DRY_RUN
      value: "true"
    - name: SLACK_MEMBERSHIP_WELCOME_CHANNEL_ID
      value: CN8N938K1
    - name: SLACK_MEMBERSHIP_ADMIN_CHANNEL_ID
      value: C0314EZ719S
    - name: SLACK_MEMBERSHIP_USERGROUP_ID
      value: S01MX7W3LB0
    - name: DELTA_SCORING_ENABLED
      value: "true"
    - name: DELTA_EVENTS_ENABLED
      value: "true"
    - name: DELTA_EVENTS_CATEGORY_ID
      value: "54"
    - name: PLAYBOOK_EVENTS_ENABLED
      value: "true"
    - name: GITHUB_SCORING_ENABLED
      value: "true"
  ingresses:
    - https://security-champion-levels-backend.intern.nav.no
  accessPolicy:
    inbound:
      rules:
        - application: security-champion-stats-frontend
    outbound:
      external:
        - host: slack.com
        - host: api.slack.com
        - host: graph.microsoft.com
        - host: sikkerhet.nav.no
        - host: api.github.com
      rules:
        - application: team-catalog-backend
          cluster: prod-gcp
          namespace: org
        - application: delta-backend
          cluster: prod-gcp
          namespace: delta
  replicas:
    max: 2
    min: 2
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        groups:
          - id: "d633d27b-a470-4b9d-984e-85499f126e18"
        extra:
          - "NAVident"
  resources:
    limits:
      memory: "768Mi"
    requests:
      cpu: "10m"
      memory: "416Mi"
  envFrom:
    - secret: security-champion-stats
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: security-champion-stats-db
