FROM europe-north1-docker.pkg.dev/cgr-nav/pull-through/nav.no/jre:openjdk-25@sha256:9dacbc067eaf9681881305b13d1ac18d1a36a61e8f2c2674d75d22d383e5aadd

ENV LC_ALL='nb_NO.UTF-8' LANG='nb_NO.UTF-8' TZ='Europe/Oslo'

USER nonroot

COPY build/libs/*.jar /app/

WORKDIR /app

CMD ["app.jar"]