CREATE SCHEMA IF NOT EXISTS dbo;

CREATE TABLE IF NOT EXISTS Members (
    id VARCHAR(100) PRIMARY KEY,
    fullname VARCHAR(100) NOT NULL,
    points INT DEFAULT 0,
    create_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
