openapi: "3.0.3"
info:
  title: "security-champion-stats"
  description: "Api for security champion stats"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
  - url: "https://security-champion-levels-backend.intern.nav.no"
paths:
  /api/members:
    get:
      tags:
        - member
      description: "Get all members"
      operationId: getMembers
      responses:
        200:
          description: "Members found"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Member"
  /api/points:
    post:
      tags:
        - points
      description: "Add points for a member"
      operationId: addPoints
      responses:
        200:
          description: "Member is found and points added"
          content:
            application/json:
              schema:
                type: string
        404:
          description: "Member is was not found"
          content:
            application/json:
              schema:
                type: string

        400:
          description: "Invalid values"
          content:
            application/json:
              schema:
                type: string

        500:
          description: "Server Error"
          content:
            application/json:
              schema:
                type: string


components:
  schemas:
    Member:
      type: object
      properties:
        id:
          type: string
          description: "User id"
        fullname:
          type: string
          description: "Full name of a user"
        points:
          description: "Amount of points user has"
          type: integer
        email:
          type: string
          description: "Users email address"