export const hackerCopy = {
	brand: "SEC_HUB",
	navigation: {
		version: "v1.33.7 // build l33t",
		prompt: "~/sechub $ ls",
		statusTitle: "// SYSTEM STATUS",
		admin: "admin/ [sudo]",
		history: "  archived_ops/",
	},
	header: {
		promptPrefix: "root@sechub:~# ./welcome.sh --agent=",
		title: "ACCESS GRANTED",
		button: "[ HACK THE MAINFRAME ]",
	},
	statusUnavailable: "uid unavailable (champion)",
	subtitle:
		"Welcome back, operative. The mainframe has missed you. (It's an Excel sheet. Don't tell anyone.)",
	dossier: {
		title: "dossier_CLASSIFIED.txt",
		heading: "AGENT DOSSIER",
		active: "● ACTIVE OPERATIVE",
		pending: "○ RECRUIT PENDING",
		secret: "TOP SECRET // EYES ONLY",
		fields: ["CODENAME", "REAL NAME", "RECRUITED", "CLEARANCE", "SPECIALTY"],
		mission:
			"MISSION: Infiltrate your team. Spread secure coding. Leave no SQL injection behind.",
		selfDestruct:
			"This message will not self-destruct. We don't have the budget.",
		unknownRecruitment: "CLASSIFIED",
		pendingRecruitment: "PENDING RECRUITMENT",
		realNameUnavailable: "Name unavailable",
		allegedly: "(allegedly)",
	},
	status: [
		"firewall ........ OK",
		"coffee .......... LOW",
		"hoodie .......... ON",
		"sunglasses ...... INDOORS",
	],
	missions: [
		'Saying "have you threat-modelled that?"',
		"Rotating secrets nobody knew existed",
		"Locking other people's laptops",
		"Reading CVEs for fun",
	],
	events: {
		title: "bash — ~/ops",
		upcomingCommand: "$ ls ./incoming_transmissions",
		pastCommand: "$ ls ./archived_ops",
		upcomingEmpty: "No incoming transmissions.",
		pastEmpty: "No archived transmissions.",
		unavailable: "We couldn't load event transmissions. Try again later.",
		upcomingPermissions: "-rw-r--r--",
		pastPermissions: "-r--r--r--",
		unknownFile: "untitled",
	},
	score: {
		command: "$ cat /proc/self/xp",
		points: "XP_POINTS",
		level: "RANK",
		position: "SEASON_POSITION",
		humanPointsPrefix: "(that's ",
		humanPointsSuffix: " in human)",
		nextLevelPrefix: "upgrading to ",
		nextLevelSuffix: "...",
		topLevel: "Top clearance achieved. The server room is yours.",
		unavailable: "We couldn't load your season score. Try again later.",
		loading: "Loading current-season score…",
		remainingSuffix: " xp remaining",
	},
	leaderboard: {
		command: "$ sudo cat /etc/most_wanted",
		rank: "RANK",
		operative: "OPERATIVE",
		threat: "THREAT LEVEL",
		xp: "XP",
		class: "CLASS",
		note: "// your name could be here. or at least spelled correctly.",
		unavailable: "We couldn't load the leaderboard. Try again later.",
		loading: "Loading the leaderboard…",
		seasonLabel: "season",
		operativeCount: "operatives online",
		emptySeason: "No current season",
		threatPrefix: "Threat level ",
		threatOf: " of 20",
	},
	hack: {
		label: "Mainframe access simulation",
		success: "YOU'RE IN.",
		message: "+0 xp. Nice try. Go attend a meetup instead.",
		close: "[ click to exit ]",
		closeLabel: "Close mainframe simulation",
	},
	rankJokes: [
		"you are the one, Neo",
		"close enough to smell root",
		"close enough to smell root",
		"the mainframe believes in you",
	],
	onlineMarker: "//",
	clearance: {
		novice: "Level 1 — can open the fridge",
		apprentice: "Level 2 — knows where the good coffee is",
		adept: "Level 3 — has seen the server room (from outside)",
		expert: "Level ∞ — is the server room",
	},
	hackLines: [
		"> initiating handshake with mainframe.corp.local ...",
		"> bypassing firewall (asking nicely) ...",
		"> brute-forcing password: hunter2 ... OK",
		"> decrypting 4096-bit RSA in 60 seconds like in Swordfish ...",
		"> downloading more RAM ............ 100%",
		"> disabling MFA ... ERROR: MFA is actually good. Skipping.",
		"> enhancing ... enhancing ... ENHANCE.",
		"> root shell acquired.",
	],
	settings: {
		phosphor: "Phosphor",
		matrix: "Matrix",
		amber: "Amber",
		swordfish: "Swordfish",
		rain: "Matrix rain",
		crt: "CRT scanlines",
	},
	labels: {
		loadingEvents: "Loading incoming transmissions…",
		meetup: "meetup",
		event: "event",
		eventLinkSuffix: ", ",
	},
	footer:
		"no mainframes were harmed in the making of this programme · hack responsibly · there is no spoon",
} as const;
