name: Build and deploy frontend
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/deploy-frontend.yaml'
      - 'apps/frontend/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: apps/frontend

jobs:
  test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@739bfe42ca9233c5e6aca07c1a25a9d34aca49b0 # ratchet:pnpm/action-setup@v4
        with:
          version: '10'
          package_json_file: apps/frontend/package.json
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # ratchet:actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://npm.pkg.github.com/'
          cache: 'pnpm'
          cache-dependency-path: apps/frontend/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: pnpm run build
      - uses: nais/docker-build-push@751a312f0803eb96a05a41fadf51be19b7be362c # ratchet:nais/docker-build-push@v0
        id: docker-push
        with:
          team: appsec
          build_secrets: NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}
          build_args: CACHE_BUST=${{ inputs.cachekey }}
          dockerfile: apps/frontend/Dockerfile
          docker_context: apps/frontend
          image_suffix: frontend
      - uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: apps/frontend/.nais/nais.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}
    outputs:
      image: ${{ steps.docker-push.outputs.image }}


  trivy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write # for dependency graph & sarif
      security-events: write # push sarif to github security
    needs: test-build
    steps:
      - uses: nais/login@d6ab5d83f735e9f155eb9d7d29cd20ae46820ea9 # ratchet:nais/login@v0
        with:
          team: appsec
      - name: Scan docker image for secrets
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: '${{ needs.test-build.outputs.image }}'
          format: 'sarif'
          scanners: 'secret'
          output: 'trivy.sarif'
      - uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e
        with:
          sarif_file: 'trivy.sarif'
