name: Build and deploy frontend
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/deploy-frontend.yaml'
      - 'apps/frontend/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: apps/frontend

jobs:
  test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: '11'
          package_json_file: apps/frontend/package.json
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
          registry-url: 'https://npm.pkg.github.com/'
      - run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: pnpm run test
      - run: pnpm run build
      - uses: nais/docker-build-push@8e41f1f58749b9248e376c25d33bfbdd2b1163c0 # v0
        id: docker-push
        with:
          team: appsec
          build_secrets: NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}
          build_args: CACHE_BUST=${{ inputs.cachekey }}
          dockerfile: apps/frontend/Dockerfile
          docker_context: apps/frontend
          image_suffix: frontend
      - uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: apps/frontend/.nais/nais.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}
    outputs:
      image: ${{ steps.docker-push.outputs.image }}


  trivy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write # for dependency graph & sarif
      security-events: write # push sarif to github security
    needs: test-build
    steps:
      - uses: nais/login@40b72a35a18ddf2ad74b632461139ab838cc2a2f # v0
        with:
          team: appsec
      - name: Scan docker image for secrets
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: '${{ needs.test-build.outputs.image }}'
          format: 'sarif'
          scanners: 'secret'
          output: 'trivy.sarif'
      - uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4.37.7
        with:
          sarif_file: 'trivy.sarif'
