name: Run frontend tests
on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'apps/frontend/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: apps/frontend

jobs:
  test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: '11'
          package_json_file: apps/frontend/package.json
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
          registry-url: 'https://npm.pkg.github.com/'
      - run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: pnpm run test
      - run: pnpm run build
      - uses: nais/docker-build-push@8e41f1f58749b9248e376c25d33bfbdd2b1163c0 # v0
        id: docker-push
        with:
          team: appsec
          build_secrets: NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}
          build_args: CACHE_BUST=${{ inputs.cachekey }}
          push_image: false
          dockerfile: apps/frontend/Dockerfile
          docker_context: apps/frontend
          image_suffix: frontend
