name: Run frontend tests
on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'apps/frontend/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: apps/frontend

jobs:
  test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: '11'
          package_json_file: apps/frontend/package.json
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '24'
          registry-url: 'https://npm.pkg.github.com/'
      - run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: pnpm run test
      - run: pnpm run build
      - uses: nais/docker-build-push@05dbb6091b30bd84279c6d64a45ef8782fd410a5 # v0
        id: docker-push
        with:
          team: appsec
          build_secrets: NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}
          build_args: CACHE_BUST=${{ inputs.cachekey }}
          push_image: false
          dockerfile: apps/frontend/Dockerfile
          docker_context: apps/frontend
          image_suffix: frontend
